name: GitHub action release for pipeline in Node.js

runs:
  using: "composite"
  steps: 
  
    ############# Release #############

    - name: Release binary artifacts
      run: ./release.ps1
      shell: bash
