name: GitHub action release for pipeline in Node.js
description: GitHub action release for pipeline in Node.js

inputs:
  npm-user:
    description: 'Username of npm account to create release'
    required: false
  npm-pass:
    description: 'Password of npm account to create release'
    required: false
  npm-email:
    description: 'Email of npm account to create release'
    required: false
  npm-token:
    description: 'Publish token for npm release'
    required: false

runs:
  using: "composite"
  steps: 
  
    ############# Release #############

    - name: Release binary artifacts
      run: ./release.ps1
      env:
        NPM_USER: ${{ inputs.npm-user }}
        NPM_PASS: ${{ inputs.npm-pass }}
        NPM_EMAIL: ${{ inputs.npm-email }}
        NPM_TOKEN: ${{ inputs.npm-token }}
      shell: bash
