name: GitHub action release for pipeline in .NET

inputs:
  nuget-key:
    description: 'Nuget key to create release'
    required: true

runs:
  using: "composite"
  steps: 
  
    ############# Release #############

    - name: Release binary artifacts
      run: ./release.ps1
      env:
        NUGET_KEY: ${{ inputs.nuget-key }}
      shell: bash
