name: GitHub action for pipeline in .NET

inputs:
  nuget-key:
    description: 'Nuget key to create release'
    required: true

outputs:
  build_number: 
    description: "Build number"
    value: ${{ steps.build_info.outputs.build_number }}
  component_version: 
    description: "Component version"
    value: ${{ steps.build_info.outputs.component_version }}
  component_name: 
    description: "Component name"
    value: ${{ steps.build_info.outputs.component_name }}

runs:
  using: "composite"
  steps: 
  
    ############# Prepare #############

    - name: Save build number and component version
      id: build_info
      run: |
        echo "##[set-output name=build_number;]$GITHUB_RUN_NUMBER"
        echo "##[set-output name=component_version;]$(jq -r '.version' ./component.json)"
        echo "##[set-output name=component_name;]$(jq -r '.name' ./component.json)"
      shell: bash
   
    - name: Install powershell
      run: |
        sudo apt-get update
        sudo apt-get install -y wget apt-transport-https
        wget -q https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb
        sudo dpkg -i packages-microsoft-prod.deb
        sudo apt-get update
        sudo apt-get install -y powershell
      shell: bash

    ############# Build and test #############
    
    - name: Build the component
      run: ./build.ps1
      shell: bash

    - name: Test the component
      run: ./test.ps1
      shell: bash

    ############# Release #############

    - name: Release binary artifacts
      run: ./release.ps1
      env:
        NUGET_KEY: ${{ inputs.nuget-key }}
      shell: bash

    ############# Clear #############

    # - name: Clean temporary build artifacts
    #   if: ${{ always() }}
    #   run: ./clean.ps1
    #   shell: bash
    