name: GitHub action release for pipeline in Java
description: GitHub action release for pipeline in Java

inputs:
  m2-user:
    description: 'Username of mvn account to create release'
    required: true
  m2-pass:
    description: 'Password of mvn account to create release'
    required: true
  gpg-public-key:
    description: 'GPG public key'
    required: true
  gpg-private-key:
    description: 'GPG private key'
    required: true
  gpg-keyname:
    description: 'GPG keyname to create release'
    required: true
  gpg-passphrase:
    description: 'GPG phrase to create release'
    required: true

runs:
  using: "composite"
  steps: 
  
    ############# Release #############

    - name: Release binary artifacts
      run: ./release.ps1
      env:
        M2_USER: ${{ inputs.m2-user }}
        M2_PASS: ${{ inputs.m2-pass }}
        GPG_PUBLIC_KEY: ${{ inputs.gpg-public-key }}
        GPG_PRIVATE_KEY: ${{ inputs.gpg-private-key }}
        GPG_KEYNAME: ${{ inputs.gpg-keyname }}
        GPG_PASSPHRASE: ${{ inputs.gpg-passphrase }}
      shell: bash
