name: GitHub action release for pipeline in Java

inputs:
  m2-user:
    description: 'Username of mvn account to create release'
    required: true
  m2-pass:
    description: 'Password of mvn account to create release'
    required: true
  gpg-keyname:
    description: 'GPG keyname to create release'
    required: true
  gpg-passphrase:
    description: 'GPG phrase to create release'
    required: true

runs:
  using: "composite"
  steps: 
  
    ############# Release #############

    - name: Release binary artifacts
      run: ./release.ps1
      env:
        M2_USER: ${{ inputs.m2-user }}
        M2_PASS: ${{ inputs.m2-pass }}
        GPG_KEYNAME: ${{ inputs.gpg-keyname }}
        GPG_PASSPHRASE: ${{ inputs.gpg-passphrase }}
      shell: bash
